package com.choodon.rpc.base.common;

public class RPCConstants {
    public static final String SERVICE_KEY = "serviceKey";
    public static final String CLUSTER_KEY = "clusterKey";
    public static final String SERVICE_HAND_ID = "handId";
    public static final String SERVICE_PROTOCOL = "choodon";
    public static final String CALL_TYPE_SYNC = "sync";
    public static final String CALL_TYPE_ASYNC_FUTURE = "future";
    public static final String CALL_TYPE_ASYNC_CALLBACK = "callback";
    public static final String DEFAULT_VERSION = "1.0";
    public static final String DEFAULT_GROUP = "default";
    public static final String DEFAULT_SERIALIZATION = "json";
    public static final String PROTOCOL_SEPARATOR = "://";
    public static final String PATH_SEPARATOR = "/";
    public static final String NODE_TYPE_SERVICE = "service";
    public static final String DEFAULT = "default";
    public static final String DEFAULT_CHARACTER = "utf-8";
    public static final String CATAGRAY = "catagray";
    public static final String PROVIDER_CATAGRAY = "provider";
    public static final String CONSUMER_CATAGRAY = "consumer";
    public static final String PROTOSTUFF = "protostuff";
    public static final String KRYO = "kryo";
    public static final String FASTJSON = "fastjson";
    public static final String SEPARATOR = "/";
    public static final String ID = "id";
    public static final String SERIALIZER = "serializer";
    public static final String PROTOCOL = "protocol";
    public static final String NETTY = "netty";
    public static final String NETTY_TCP = "netty.tcp";
    public static final String NETTY_HTTP = "netty.http";
    public static final String ZOOKEEPER = "zookeeper";
    public static final String TCP = "tcp";
    public static final String HTTP = "http";
    public static final String MQ = "mq";
    public static final String IP = "ip";
    public static final String PORT = "port";
    public static final String APPID = "appId";
    public static final String SERVICE_ID = "serviceId";
    public static final String GROUP = "group";
    public static final String VERSION = "version";
    public static final String METHOD_DES = "method_des";
    public static final String LOAD_BALANCE_ROUNDROBIN = "roundrobin";
    public static final String LOAD_BALANCE_RANDOM = "random";
    public static final String HA_STRATEGY_FAILOVER = "failover";
    public static final String HA_STRATEGY_FAILFAST = "failfast";
}
